=== liketechnik/infoDisplay/bot/src/main/resources/language.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2016-2017  Florian Warzecha <flowa2000@gmail.com>
  ~
  ~ This file is part of infoDisplay.
  ~
  ~ infoDisplay is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ infoDisplay is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  ~
  ~ infoDisplay uses TelegramBots Java API <https://github.com/rubenlagus/TelegramBots> by Ruben Bermudez.
  ~ TelegramBots API is licensed under GNU General Public License version 3 <https://www.gnu.org/licenses/gpl-3.0.de.html>.
  ~
  ~ infoDisplay uses parts of the Apache Commons project <https://commons.apache.org/>.
  ~ Apache commons is licensed under the Apache License Version 2.0 <http://www.apache.org/licenses/>.
  ~
  ~ infoDisplay uses vlcj library <http://capricasoftware.co.uk/#/projects/vlcj>.
  ~ vlcj is licensed under GNU General Public License version 3 <https://www.gnu.org/licenses/gpl-3.0.de.html>.
  ~
  ~ Thanks to all the people who contributed to the projects that make this
  ~ program possible.
  -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="name"  type="xs:language"/>

    <xs:attribute name="command" type="xs:token"/>
    <xs:attribute name="position" type="xs:nonNegativeInteger"/>
    <xs:attribute name="case" type="xs:token"/>


    <xs:element name="part">
        <xs:complexType mixed="true">
            <xs:simpleContent>
                <xs:extension base="xs:token">
                    <xs:attribute ref="position" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="case">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="part" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="case" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="command_message">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="part" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="case" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="command" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="command_package">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="command_message" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="command" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="language">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="command_message" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="command_package" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== liketechnik/infoDisplay/src/main/java/org/telegram/bot/messages/en.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--
  ~ Copyright (C) 2016  Florian Warzecha <flowa2000@gmail.com>
  ~
  ~ This file is part of infoDisplay.
  ~
  ~ infoDisplay is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ infoDisplay is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  ~
  ~ infoDisplay uses TelegramBots Java API <https://github.com/rubenlagus/TelegramBots> by Ruben Bermudez.
  ~ TelegramBots API is licensed under GNU General Public License version 3 <https://www.gnu.org/licenses/gpl-3.0.de.html>.
  ~
  ~ infoDisplay uses parts of the Apache Commons project <https://commons.apache.org/>.
  ~ Apache commons is licensed under the Apache License Version 2.0 <http://www.apache.org/licenses/>.
  ~
  ~ infoDisplay uses vlcj library <http://capricasoftware.co.uk/#/projects/vlcj>.
  ~ vlcj is licensed under GNU General Public License version 3 <https://www.gnu.org/licenses/gpl-3.0.de.html>.
  ~
  ~ Thanks to all the people who contributed to the projects that make this
  ~ program possible.
  -->

<!-- Please use '/n>' to produce a newline character in output-->

<language xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="language.xsd">
    <name>en</name>
    <command_message command="start_command">
        <case case="userUnknown">
            <part position="1">Hello</part>
            <part position="2">,/n>as you know this bot, you probably already know how to use it, although you can use
                the '/help' command. If you do not know it yet, it probably will not be useful for you. If you have a
                question concerning this bot, feel free to ask it via '/ask'.</part>
        </case>
        <case case="userKnown">
            <part position="1">Hello</part>
            <part position="2">,/n>nice to see you again. I hope you still know all the commands, if not
                the '/help' command will always be you guide.</part>
        </case>
    </command_message>
    <command_message command="stop_command">
        <part position="1">Bye</part>
        <part position="2">./n>It was nice to work with you.</part>
    </command_message>
    <command_message command="send_on_error_occurred_command">
        <case case="terminating">
            <part position="1">The bot was terminated because of an internal error. Please advise the administrator of
                this event.</part>
        </case>
        <case case="not_terminating">
            <part position="1">An internal error occurred while processing your request. Please contact the
                administrator.</part>
        </case>
    </command_message>
    <command_message command="register_command">
        <case case="alreadyRegistered">
            <part position="1">You are already registered. Your telegram userID is: </part>
        </case>
        <case case="registrationRequestSent">
            <part position="1">You have already sent a registration request. Your telegram userID is:</part>
        </case>
        <case case="newRegistrationRequest">
            <part position="1">The administrator will be advised that you want to be registered. That why he will get in
                contact with you soon. Your telegram userID is: </part>
        </case>
        <case case="toAdmin">
            <part position="1">The user </part>
            <part position="2">wants to get registered. His userID is: </part>
        </case>
    </command_message>
    <command_message command="id_command">
        <part position="1">Your telegram userID is:</part>
        <part position="2">The chatID is:</part>
    </command_message>
    <command_message command="help_command">
        <part position="1">*Help*/n>/n>
            _Description_/n>
            Mit diesem Bot kannst Du Bilder an das virtuelle Brett hochladen, bearbeiten und wieder löschen. Als
            Administrator kannst du auch veraltete Bilder *anderer* löschen und deren Eigenschaften bearbeiten./n>/n>
            _How to use me:_/n>
        </part>
    </command_message>
    <command_message command="administrator_command">
        <part position="1">Ersteller / Administrator dieses Bots ist @liketechnik2000.</part>
    </command_message>
</language>

=== liketechnik/infoDisplay/src/main/java/org/telegram/bot/messages/ger.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--
  ~ Copyright (C) 2016  Florian Warzecha <flowa2000@gmail.com>
  ~
  ~ This file is part of infoDisplay.
  ~
  ~ infoDisplay is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ infoDisplay is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  ~
  ~ infoDisplay uses TelegramBots Java API <https://github.com/rubenlagus/TelegramBots> by Ruben Bermudez.
  ~ TelegramBots API is licensed under GNU General Public License version 3 <https://www.gnu.org/licenses/gpl-3.0.de.html>.
  ~
  ~ infoDisplay uses parts of the Apache Commons project <https://commons.apache.org/>.
  ~ Apache commons is licensed under the Apache License Version 2.0 <http://www.apache.org/licenses/>.
  ~
  ~ infoDisplay uses vlcj library <http://capricasoftware.co.uk/#/projects/vlcj>.
  ~ vlcj is licensed under GNU General Public License version 3 <https://www.gnu.org/licenses/gpl-3.0.de.html>.
  ~
  ~ Thanks to all the people who contributed to the projects that make this
  ~ program possible.
  -->

<!-- Please use '/n>' to produce a newline character in output-->

<language xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="language.xsd">
    <name>ger</name>
    <command_message command="start_command">
        <case case="userUnknown">
            <part position="1">Hallo</part>
            <part position="2">,/n>da Du diesen Bot schon kennst, weißt du wahrscheinlich auch schon wie er zu benutzen
                ist, auch wenn du den '/help' Befehl benutzen kannst. Wenn du diesen Bot noch nicht kennst, wird er
                wahrscheinlich er dir wahrscheinlich nichts nutzen. Wenn du eine Frage zu diesem Bot hast, benutze
                einfach den '/ask' Befehl.</part>
        </case>
        <case case="userKnown">
            <part position="1">Hallo</part>
            <part position="2">,/n>schön dich wieder zu sehen. Ich hoffe dir sind noch alle Befehle bekannt, wenn nicht
                steht dir der '/help' Befehl mit Rat und Tat zur Seite.</part>
        </case>
    </command_message>
    <command_message command="stop_command">
        <part position="1">Tschüss</part>
        <part position="2">./n>War 'ne schöne Zeit mit dir.</part>
    </command_message>
    <command_message command="send_on_error_occurred_command">
        <case case="terminating">
            <part position="1">Der Bot ist aufgrund eines Fehlers beendet worden. Bitte informiere den Administrator.
            </part>
        </case>
        <case case="not_terminating">
            <part position="1">Es ist ein interner Fehler aufgetreten. Benachrichtige bitte den Administrator.</part>
        </case>
    </command_message>
    <command_message command="register_command">
        <case case="alreadyRegistered">
            <part position="1">Du bist bereits registriert. Deine Telegram userID ist: </part>
        </case>
        <case case="registrationRequestSent">
            <part position="1">Du hast bereits eine Anfrage zur Registrierung gesendet. Deine Telegram userID ist: </part>
        </case>
        <case case="sendRegistrationRequest">
            <part position="1">Ich werde den Administratot über deine Anfrage zur Registrierung informieren. Er wird
                dich deshalb in Kürze kontaktieren. Deine Telegram userID ist: </part>
        </case>
        <case case="toAdmin">
            <part position="1">Der Benutzer </part>
            <part position="2">möchte registriert werden. Seine userID ist: </part>
        </case>
    </command_message>
    <command_message command="id_command">
        <part position="1">Deine Telegram userID ist:</part>
        <part position="2">Die chatID ist:</part>
    </command_message>
    <command_message command="help_command">
        <part position="1">*Hilfe*/n>/n>
            _Beschreibung_/n>
            Mit diesem Bot kannst Du Bilder an das virtuelle Brett hochladen, bearbeiten und wieder löschen. Als
            Administrator kannst du auch veraltete Bilder *anderer* löschen und deren Eigenschaften bearbeiten./n>/n>
            _How to use me:_/n>
        </part>
    </command_message>
    <command_message command="administrator_command">
        <part position="1">Ersteller / Administrator dieses Bots ist @liketechnik2000.</part>
    </command_message>
    <command_package command="pinPictureCommand">
        <command_message command="pin_picture_command">
            <case case="no_permission">
                <part position="1">Du bist nicht berechtigt Bilder hochzuladen./n>
                    Benutze /register um als berechtigte Person eingetragen zu werden./n></part>
            </case>
            <case case="permission">
                <part position="1">Bitte sende mir einen Namen für dein Bild.</part>
            </case>
        </command_message>
    </command_package>
</language>
