=== liketechnik/infoDisplay/src/main/java/org/telegram/bot/messages/language.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~ Copyright (C) 2016  Florian Warzecha <flowa2000@gmail.com>
  ~
  ~ This file is part of infoDisplay.
  ~
  ~ infoDisplay is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ infoDisplay is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  ~
  ~ infoDisplay uses TelegramBots Java API <https://github.com/rubenlagus/TelegramBots> by Ruben Bermudez.
  ~ TelegramBots API is licensed under GNU General Public License version 3 <https://www.gnu.org/licenses/gpl-3.0.de.html>.
  ~
  ~ infoDisplay uses parts of the Apache Commons project <https://commons.apache.org/>.
  ~ Apache commons is licensed under the Apache License Version 2.0 <http://www.apache.org/licenses/>.
  ~
  ~ infoDisplay uses vlcj library <http://capricasoftware.co.uk/#/projects/vlcj>.
  ~ vlcj is licensed under GNU General Public License version 3 <https://www.gnu.org/licenses/gpl-3.0.de.html>.
  ~
  ~ Thanks to all the people who contributed to the projects that make this
  ~ program possible.
  -->
<!--<!ENTITY % languages -->

<!ELEMENT lang_name (#PCDATA)>

<!ELEMENT command (#PCDATA)>

<!ELEMENT language (lang_name,(command_messages)+)>
    <!ELEMENT command_messages (command,(part)+)>
        <!ELEMENT part (position,message)>
            <!ELEMENT position (#PCDATA)>
            <!ELEMENT message (#PCDATA)>

=== liketechnik/infoDisplay/src/main/java/org/telegram/bot/messages/english.xml
<?xml version="1.0" encoding="UTF-8" ?>


<!DOCTYPE language SYSTEM "language.dtd">
<language>
    <lang_name>en</lang_name>
    <command_messages>
        <command>start_command</command>
        <part>
            <position>1</position>
            <message>Hello </message>
        </part>
        <part>
            <position>2</position>
            <message>,\nif you know this bot, you probably already know how to use it, although you can use the '/help'
                command. If not, then it will not be useful for you. If you have a question concerning
                this bot, feel free to ask it via '/ask'.\n\nYou can set the language via the '/language' command."
                ;</message>
        </part>
    </command_messages>
</language>
